//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase_6_DBDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camisa
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tela { get; set; }
        public string Talla { get; set; }
    }
}
